name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    branches:
      - master
    types:
      - published

jobs:
  lint:
    name: Lint code using eslint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js 14
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install project dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Run eslint
        run: |
          yarn lint

  build:
    name: Build frontend
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js 14
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install project dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Prepare build environment variables
        id: branch_info
        run: |
          branch_name=${GITHUB_REF##*/}
          short_sha=${GITHUB_SHA:0:7}
          echo "##[set-output name=branch_name;]${branch_name}"
          echo "##[set-output name=short_sha;]${short_sha}"

          if [ "$branch_name" = "master" || ${{ github.event_name == 'release' }} ]; then
            echo "OPENSENSEMAP_API_URL=https://api.opensensemap.org" >> $GITHUB_ENV
            echo "OPENSENSEMAP_MAPTILES_URL=${{ secrets.OPENSENSEMAP_MAPTILES_URL_PROD }}" >> $GITHUB_ENV
          else
            echo "OPENSENSEMAP_API_URL=https://api.testing.opensensemap.org" >> $GITHUB_ENV
            echo "OPENSENSEMAP_MAPTILES_URL=https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" >> $GITHUB_ENV
          fi

      - name: Build
        run: |
          npx grunt build --target=build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}

      - name: Build container image and push to Docker Hub (not for PRs)
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name == 'push' }} || ${{ github.event_name == 'release' && github.event.action == 'published' }}
          tags: ${{ secrets.IMAGE_NAME }}:${{ steps.branch_info.outputs.branch_name }},${{ secrets.IMAGE_NAME }}:${{ steps.branch_info.outputs.branch_name }}-${{ steps.branch_info.outputs.short_sha }}
          context: ./
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
          target: staticfiles
